image:
  registry: ghcr.io/hiboyang
  repository: batch-processing-gateway
  tag: main

replicas: 1

namespace: bpg

resources:
  requests:
    memory: '2G'
    cpu: "0.5"
  limits:
    memory: '2G'
    cpu: "0.5"


ingress:
  endpoint: 'bpg.values.example.com'
  tlsSecretName: 'bpg.tls.name.values.example'

# Config is provided as a base64-encoded,
# compressed content which will be projected into pods as /app/app-config.gz.
encodedConfig:

plainConfig:

# For Swagger UI which visualizes API specs.
swagger:
  image: 'swaggerapi/swagger-ui:v4.14.0'
