apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  generation: 3
  name: bpg-swagger-ingress
spec:
  rules:
    - host: {{ .Values.ingress.endpoint }}
      http:
        paths:
          - path: /(openapi\.(json|yaml)$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bpg
                port:
                  number: 80
          - path: /swagger
            pathType: ImplementationSpecific
            backend:
              service:
                name: bpg-swagger-ui
                port:
                  number: 80
          - path: /(.*\.css$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bpg-swagger-ui
                port:
                  number: 80
          - path: /(.*\.js$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bpg-swagger-ui
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.endpoint }}
      secretName: {{ .Values.ingress.tlsSecret }}
